name: Twitter Video Bot
on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 ghante mein automation
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Bot
        env:
          # Inhe GitHub Secrets ke names se match karein
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          GDRIVE_JSON: ${{ secrets.GDRIVE_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          TW_API_KEY: ${{ secrets.TW_API_KEY }}
          TW_API_SECRET: ${{ secrets.TW_API_SECRET }}
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_SECRET: ${{ secrets.TW_ACCESS_SECRET }}
        run: |
          pip install tweepy requests google-api-python-client google-auth yt-dlp
          python bot.py
